export enum OperatorType {
    IS = 'Text_IS',
    HAS = 'Text_HAS',
    MAKE = 'Text_MAKE',
    AND = 'Text_AND',
    NOT = 'Text_NOT',
    ON = 'Text_ON',
    NEAR = 'Text_NEAR',
    FACING = 'Text_FACING',
    LONELY = 'Text_LONELY',
    FEAR = 'Text_FEAR',
    EAT = 'Text_EAT',
    FOLLOW = 'Text_FOLLOW',
    MIMIC = 'Text_MIMIC',
    IDLE = 'Text_IDLE',
    POWERED = 'Text_POWERED',
    WITHOUT = 'Text_WITHOUT',
    ABOVE = 'Text_ABOVE',
    BELOW = 'Text_BELOW',
    FEELING = 'Text_FEELING',
    PLAY = 'Text_PLAY',
    OFTEN = 'Text_OFTEN',
    SELDOM = 'Text_SELDOM',
    NEVER = 'Text_NEVER',
}